### PR TITLE
Enforce formatting

### PR DESCRIPTION
**Pull request by alejandrosame**

### CODE REVIEW

**Comment by r0hit05** [comment]
Have a nice weekend!

**Comment by albertchae** [comment]
are you all running this with `nix fmt` or something else?

**Comment by mightyiam** [comment]
Yes, `nix fmt`, if I remember correctly. Does that not work for you?

**Comment by albertchae** [comment]
It worked for us, just curious if you were invoking it in a different way.

**Comment by mightyiam** [comment]
I have alejandra set up in my editor.

**Pull request merged**
