### PR TITLE
dmt-core: init at 2.1.0

### PR DESCRIPTION
**Pull request by jasonodoom**
This PR packages [DMT-core](https://gitlab.com/dmt-development/dmt-core) lib as funded by NGI through NLnet. DeviceModelingToolkit (DMT) is a Python tool targeted at helping modeling engineers extract model parameters, run circuit and TCAD simulations and automate their infrastructure.

### CODE REVIEW

**Comment by fricklerhandwerk** [comment]
https://buildbot.ngi.nixos.org/#/builders/199/builds/4
```log
error: evaluation aborted with the following error message: 'lib.customisation.callPackageWith: Function called without required argument "buildPythonApplication" at /nix/store/8m88lx6lbx32vc7m3ax6czy26bcw59bk-source/pkgs/by-name/dmt-core/package.nix:1'
```

**Comment by fricklerhandwerk** [comment]
Please run `nix fmt` to please the pre-commit check.

**Comment by jasonodoom** [comment]
> Please run `nix fmt` to please the pre-commit check.

I was going to wait for out meeting to ask. I had prior to committing :(

**Comment by jasonodoom** [comment]
Closing this PR since it's upstreamed here: https://github.com/NixOS/nixpkgs/pull/320189

**Pull request closed without merging**
