### PR TITLE
Add Libervia-backend

### LINKED ISSUE #87: Libervia-backend
Source code: https://repos.goffi.org/libervia-backend/

Part of #4

### PR DESCRIPTION
**Pull request by OPNA2608**
Closes #87

Bildschirmfoto_2024-07-16_23-28-45

Bildschirmfoto_2024-07-16_23-31-33

### CODE REVIEW

**Comment by OPNA2608** [comment]
`pytest-twisted` started failing in Nixpkgs after I started working on this: https://hydra.nixos.org/build/265306268

**Comment by OPNA2608** [comment]
Should be good to go now - licensing stuff is resolved, and everything builds on buildbot.

**Review by wegank — APPROVED** [review]

**Comment by goffi-contrib** [comment]
Wow that's great, thanks a lot for your work!

I'm not used to Nix yet, and I would like to test it. How can one test it right now, and when can we expect to see it on https://search.nixos.org ?

Thanks again!

**Comment by fricklerhandwerk** [comment]
This won't show up on search.nixos.org for now, but we have an overview of NGI-supported projects here: https://ngi-nix.github.io/ngipkgs/

You could try going through the user documentation made by @cleeyv: https://github.com/ngi-nix/ngipkgs/tree/main/deploy (ping me if you have questions)

**Comment by goffi-contrib** [comment]
great, thanks!

**Pull request merged**
