### PR TITLE
bump nixpkgs

### PR DESCRIPTION
**Pull request by alejandrosame**
I needed to bump nixpkgs as a prerequisite of #99.

However, updating the input introduced some regressions, so I decided to bump and fix on a separate PR.

### CODE REVIEW

**Comment by mightyiam** [comment]
@alejandrosame check failing.

**Comment by alejandrosame** [comment]
CI fails with `Error: Resource not accessible by integration`, which seems like a CI introduced error. 

Googling around, it looks like a permissions problem, but I'm unable to debug this @lorenzleutgeb @mightyiam .

**Comment by alejandrosame** [comment]
I just noticed, could this error be triggered because the PR is coming from a fork?

**Comment by lorenzleutgeb** [comment]
It seems like you are running into [this](https://github.com/thollander/actions-comment-pull-request#permissions). Possible workaround at #134.

**Comment by lorenzleutgeb** [comment]
Superseded by #135

**Pull request closed without merging**
